import { JSONSchemaType } from "ajv";

type CellData<T> = {
  top: number;
  left: number;
  width: number;
  height: number;
  text: T;
};

type TableData = [
  [
    CellData<"国内約定年月">,
    CellData<"国内受渡年月">,
    CellData<"銘柄コード">,
    CellData<"取引の種類">,
    CellData<"売買">,
    CellData<"自己・委託">,
    CellData<"市場">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<"現地約定年月">,
    CellData<"現地受渡年月日">,
    CellData<"銘 柄 名">,
    CellData<"取引通貨">,
    CellData<"決済方法">,
    CellData<"為替レート">,
    CellData<"口座区分">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<"約定数量">,
    CellData<"約定価格">,
    CellData<"約定金額">,
    CellData<"現地手数料等" | "地手数料等">,
    CellData<"現地精算金額">,
    CellData<"国内手数料">,
    CellData<"消費税">,
    CellData<"受渡金額">,
    CellData<"備考">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ]
];

export type Table = {
  data: TableData;
};

const table: JSONSchemaType<Table> = {
  type: "object",
  properties: {
    data: {
      type: "array",
      items: [
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "国内約定年月" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "国内受渡年月" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "銘柄コード" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "取引の種類" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "売買" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "自己・委託" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "市場" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 13,
          maxItems: 13,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "現地約定年月" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "現地受渡年月日" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "銘 柄 名" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "取引通貨" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "決済方法" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "為替レート" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "口座区分" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 13,
          maxItems: 13,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 13,
          maxItems: 13,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 13,
          maxItems: 13,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 13,
          maxItems: 13,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "約定数量" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "約定価格" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "約定金額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", enum: ["現地手数料等", "地手数料等"] }, // TODO: "現" が欠けることがある
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "現地精算金額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "国内手数料" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "消費税" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "受渡金額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "備考" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 13,
          maxItems: 13,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 13,
          maxItems: 13,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 13,
          maxItems: 13,
        },
      ],
      minItems: 8,
      maxItems: 8,
    },
  },
  required: ["data"],
};

export const schema = {
  table,
};
