const table0 = {
  type: "array",
  items: [
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "配当金等支払日" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "国内支払日" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "現地基準日" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "銘柄コード" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "銘 柄 名" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 10,
      maxItems: 10,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 10,
      maxItems: 10,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "分配通貨" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "外国源泉税率(%)" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "1単位あたり金額" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "決済方法" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "円貨決済用レート" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "口座区分" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "勘定設定年" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "備考" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 10,
      maxItems: 10,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 10,
      maxItems: 10,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "数量" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "配当金等金額" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "外国源泉\r徴収税額" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "外国手数料" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "外国精算金額" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "国内源泉\r徴収税額" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "国内手数料" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "消費税" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "受取金額" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 10,
      maxItems: 10,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "外  貨" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 10,
      maxItems: 10,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "円 貨" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 10,
      maxItems: 10,
    },
  ],
  minItems: 7,
  maxItems: 7,
};

const table1 = {
  type: "array",
  items: [
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { enum: ["申告レート基準日", "告レート基準日"] }, // TODO: "申" が欠けることがある
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "申告レート" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "配当金等金額(円)" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "外国源泉\r徴収税額(円)" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "国内課税所得額(円)" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "所得税" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "地方税" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "国内源泉\r徴収税額" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 9,
      maxItems: 9,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { enum: ["為替レート基準日", "替レート基準日"] }, // TODO: "為" が欠けることがある
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "為替レート" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 9,
      maxItems: 9,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "外  貨" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 9,
      maxItems: 9,
    },
    {
      type: "array",
      items: [
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { const: "円  貨" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { type: "number", minimum: 0 },
            left: { type: "number", minimum: 0 },
            width: { type: "number", minimum: 0 },
            height: { type: "number", minimum: 0 },
            text: { type: "string" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            top: { const: 0 },
            left: { const: 0 },
            width: { const: 0 },
            height: { const: 0 },
            text: { const: "" },
          },
          required: ["top", "left", "width", "height", "text"],
          additionalProperties: false,
        },
      ],
      minItems: 9,
      maxItems: 9,
    },
  ],
  minItems: 4,
  maxItems: 4,
};

export const schema = {
  table0,
  table1,
};
