import { JSONSchemaType } from "ajv";

type CellData<T> = {
  top: number;
  left: number;
  width: number;
  height: number;
  text: T;
};

type Table0Data = [
  [
    CellData<"配当金等支払日">,
    CellData<"国内支払日">,
    CellData<"現地基準日">,
    CellData<"銘柄コード">,
    CellData<"銘 柄 名">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<"分配通貨">,
    CellData<"外国源泉税率(%)">,
    CellData<"1単位あたり金額">,
    CellData<"決済方法">,
    CellData<"円貨決済用レート">,
    CellData<"口座区分">,
    CellData<"勘定設定年">,
    CellData<"備考">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<"数量">,
    CellData<"配当金等金額">,
    CellData<"外国源泉\r徴収税額">,
    CellData<"外国手数料">,
    CellData<"外国精算金額">,
    CellData<"国内源泉\r徴収税額">,
    CellData<"国内手数料">,
    CellData<"消費税">,
    CellData<"受取金額">,
    CellData<"">
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"外  貨">,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>
  ],
  [
    CellData<"円 貨">,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ]
];

export type Table0 = {
  data: Table0Data;
};

const table0: JSONSchemaType<Table0> = {
  type: "object",
  properties: {
    data: {
      type: "array",
      items: [
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "配当金等支払日" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "国内支払日" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "現地基準日" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "銘柄コード" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "銘 柄 名" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 10,
          maxItems: 10,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 10,
          maxItems: 10,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "分配通貨" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "外国源泉税率(%)" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "1単位あたり金額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "決済方法" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "円貨決済用レート" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "口座区分" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "勘定設定年" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "備考" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 10,
          maxItems: 10,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 10,
          maxItems: 10,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "数量" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "配当金等金額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "外国源泉\r徴収税額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "外国手数料" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "外国精算金額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "国内源泉\r徴収税額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "国内手数料" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "消費税" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "受取金額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 10,
          maxItems: 10,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "外  貨" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 10,
          maxItems: 10,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "円 貨" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 10,
          maxItems: 10,
        },
      ],
      minItems: 7,
      maxItems: 7,
    },
  },
  required: ["data"],
};

type Table1Data = [
  [
    CellData<"申告レート基準日" | "告レート基準日">,
    CellData<"申告レート">,
    CellData<"配当金等金額(円)">,
    CellData<"外国源泉\r徴収税額(円)">,
    CellData<"国内課税所得額(円)">,
    CellData<"所得税">,
    CellData<"地方税">,
    CellData<"国内源泉\r徴収税額">,
    CellData<"">
  ],
  [
    CellData<"為替レート基準日" | "替レート基準日">,
    CellData<"為替レート">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"外  貨">,
    CellData<string>,
    CellData<string>,
    CellData<string>
  ],
  [
    CellData<string>,
    CellData<string>,
    CellData<"円  貨">,
    CellData<string>,
    CellData<string>,
    CellData<string>,
    CellData<"">,
    CellData<"">,
    CellData<"">
  ]
];

export type Table1 = {
  data: Table1Data;
};

const table1: JSONSchemaType<Table1> = {
  type: "object",
  properties: {
    data: {
      type: "array",
      items: [
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: {
                  type: "string",
                  enum: ["申告レート基準日", "告レート基準日"], // TODO: "申" が欠けることがある
                },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "申告レート" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "配当金等金額(円)" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "外国源泉\r徴収税額(円)" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "国内課税所得額(円)" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "所得税" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "地方税" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "国内源泉\r徴収税額" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 9,
          maxItems: 9,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: {
                  type: "string",
                  enum: ["為替レート基準日", "替レート基準日"], // TODO: "為" が欠けることがある
                },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "為替レート" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 9,
          maxItems: 9,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "外  貨" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 9,
          maxItems: 9,
        },
        {
          type: "array",
          items: [
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string", const: "円  貨" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", minimum: 0 },
                left: { type: "number", minimum: 0 },
                width: { type: "number", minimum: 0 },
                height: { type: "number", minimum: 0 },
                text: { type: "string" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
            {
              type: "object",
              properties: {
                top: { type: "number", const: 0 },
                left: { type: "number", const: 0 },
                width: { type: "number", const: 0 },
                height: { type: "number", const: 0 },
                text: { type: "string", const: "" },
              },
              required: ["top", "left", "width", "height", "text"],
              additionalProperties: false,
            },
          ],
          minItems: 9,
          maxItems: 9,
        },
      ],
      minItems: 4,
      maxItems: 4,
    },
  },
  required: ["data"],
};

export const schema = {
  table0,
  table1,
};
